[Variables]
TimetableSkin=Timetable.ini

BarHeight=30

IconSize=(#BarHeight# - 2)
IconY=1

ImagesFolder=#@#Images\

; 'Light' and 'Dark' variable suffix refers to theme not color

TimetableImageLight=#ImagesFolder#TimetableLight.png
ThemeIconLight=#ImagesFolder#LightThemeIcon.png
FitIconLight=#ImagesFolder#FitIconDark.png
SettingsIconLight=#ImagesFolder#SettingsIconDark.png
RefreshIconLight=#ImagesFolder#ResetIconDark.png
NextIconLight=#ImagesFolder#NextIconDark.png
ReturnIconLight=#ImagesFolder#ReturnIconDark.png
DropdownIconLight=#ImagesFolder#DropdownIconDark.png
PrimaryColorLight=230,230,230
SecondaryColorLight=255,255,255
FontColorLight=0,0,0

TimetableImageDark=#ImagesFolder#TimetableDark.png
ThemeIconDark=#ImagesFolder#DarkThemeIcon.png
FitIconDark=#ImagesFolder#FitIconLight.png
SettingsIconDark=#ImagesFolder#SettingsIconLight.png
RefreshIconDark=#ImagesFolder#ResetIconLight.png
NextIconDark=#ImagesFolder#NextIconLight.png
ReturnIconDark=#ImagesFolder#ReturnIconLight.png
DropdownIconDark=#ImagesFolder#DropdownIconLight.png
PrimaryColorDark=34,34,34
SecondaryColorDark=50,50,50
FontColorDark=255,255,255

TimetableImage=C:\Users\Aritra\Documents\Rainmeter\Skins\Rainmeter Timetable SC\@Resources\Images\TimetableDark.png
ThemeIcon=C:\Users\Aritra\Documents\Rainmeter\Skins\Rainmeter Timetable SC\@Resources\Images\DarkThemeIcon.png
FitIcon=C:\Users\Aritra\Documents\Rainmeter\Skins\Rainmeter Timetable SC\@Resources\Images\FitIconLight.png
SettingsIcon=C:\Users\Aritra\Documents\Rainmeter\Skins\Rainmeter Timetable SC\@Resources\Images\SettingsIconLight.png
RefreshIcon=C:\Users\Aritra\Documents\Rainmeter\Skins\Rainmeter Timetable SC\@Resources\Images\ResetIconLight.png
NextIcon=C:\Users\Aritra\Documents\Rainmeter\Skins\Rainmeter Timetable SC\@Resources\Images\NextIconLight.png
ReturnIcon=C:\Users\Aritra\Documents\Rainmeter\Skins\Rainmeter Timetable SC\@Resources\Images\ReturnIconLight.png
DropdownIcon=C:\Users\Aritra\Documents\Rainmeter\Skins\Rainmeter Timetable SC\@Resources\Images\DropdownIconLight.png
PrimaryColor=34,34,34
SecondaryColor=50,50,50
FontColor=255,255,255

ScriptsFolder=#@#Scripts\
ImageControlsScript=#ScriptsFolder#ImageControls.lua
ThemeScript=#ScriptsFolder#Theme.lua
TimetableScript=#ScriptsFolder#Timetable.lua
SettingsScript=#ScriptsFolder#Settings.lua

UserSettings=#@#UserSettings.inc

TimetableFetcherExe=#@#TimetableFetcher\Executable\TimetableFetcher.exe
TimetableFetcherPython=#@#TimetableFetcher\Python\app.py

NotifierExe=#@#Notifier\Notifier.exe
NotifierPython=#@#Notifier\notifier.py
