[Variables]
TimetableSkin=Timetable.ini

BarHeight=30

ImagesFolder=#@#Images\

TimetableImageLight=#ImagesFolder#TimetableLight.png
ThemeIconLight=#ImagesFolder#LightThemeIcon.png
FitIconLight=#ImagesFolder#FitIconLight.png
SettingsIconLight=#ImagesFolder#SettingsIconLight.png
RefreshIconLight=#ImagesFolder#ResetIconLight.png
NextIconLight=#ImagesFolder#NextIconLight.png
ReturnIconLight=#ImagesFolder#ReturnIconLight.png
PrimaryColorLight=230,230,230
SecondaryColorLight=255,255,255
FontColorLight=255,255,255

TimetableImageDark=#ImagesFolder#TimetableDark.png
ThemeIconDark=#ImagesFolder#DarkThemeIcon.png
FitIconDark=#ImagesFolder#FitIconDark.png
SettingsIconDark=#ImagesFolder#SettingsIconDark.png
RefreshIconDark=#ImagesFolder#ResetIconDark.png
NextIconDark=#ImagesFolder#NextIconDark.png
ReturnIconDark=#ImagesFolder#ReturnIconDark.png
PrimaryColorDark=34,34,34
SecondaryColorDark=50,50,50
FontColorDark=0,0,0

TimetableImage=
ThemeIcon=
FitIcon=
SettingsIcon=
RefreshIcon=
NextIcon=
ReturnIcon=
PrimaryColor=
SecondaryColor=
FontColor=

ScriptsFolder=#@#Scripts\
ImageControlsScript=#ScriptsFolder#ImageControls.lua
ThemeScript=#ScriptsFolder#Theme.lua
TimetableScript=#ScriptsFolder#Timetable.lua
SettingsScript=#ScriptsFolder#Settings.lua

UserSettings=#@#UserSettings.inc

; Executable version
TimetableFetcher=#@#TimetableFetcher\Executable\TimetableFetcher.exe
; Python version
; TimetableFetcher=#@#TimetableFetcher\Python\app.py

; Executable version
Notifier=#@#Notifier\Notifier.exe
; Python version
; Notifier=#@#Notifier\notifier.py
